export const data = {
    firstName: "Hokuto",
    lastName: "HANDA",
    middleName: "Amanowic",
    birthDay: "16.05.1967",
    bornCountry: "JPN, Tokyo/Ýaponiýa",
    citizenship: "JPN",
    passport: "TZ1132601, 20.50.2016 ý, 20.05.2026 ý.",
    studyOfCountry: "Ýokary, JPN, Keio Uniwersiteti",
    major: "Himiýa Inzenerligi",
    position: "Infrastruktura taslamalary müdirliginiň baş menejerniň orunbasary",
    asNo: "3/-183",
    date: "03.03.2025",
    severity: true,
    border: "Balkan welaýatynyň Garabogaz şäherinde",
    organization: "karbanit öndürýan zawodyny gurmak",
};